### ISSUE TITLE
Fix rick.charts.line_chart's ymin, ymax, yinc argument

### ISSUE THREAD

**Issue by chmnata** [CityofToronto/bdit_python_utilities#15]
when using `ymax=40` and `yinc=10` the function works:
![image](https://user-images.githubusercontent.com/46324452/67576662-f8f53b00-f70c-11e9-87c1-4cc431cdf33d.png)

using `ymax=40` and `yinc=5`:
![image](https://user-images.githubusercontent.com/46324452/67576755-2510bc00-f70d-11e9-962c-f75b3070c930.png)

using just `ymax=40`:
![image](https://user-images.githubusercontent.com/46324452/67576779-3063e780-f70d-11e9-9728-6734a4fba154.png)

**Comment by radumas** [comment]
I haven't fully riddled through this `delta` calculation, but seems like there's some clash between using `ymax`, `ymin`, and `yinc`

```python
        delta = (ymax - ymin)/4
        i = 0
        while True:
            delta /= 10
            i += 1
            if delta < 10:
                break
        yinc = kwargs.get('yinc', int(round(delta+1)*pow(10,i)))
```

https://github.com/CityofToronto/bdit_python_utilities/blob/charts/charts/rick.py#L267-L274

**Comment by radumas** [comment]
At some point the y ticks were just from range `ymin`, to `ymax`

https://github.com/CityofToronto/bdit_python_utilities/blame/cae6787298bb6ee5003690fc88002aa23454af53/charts/rick.py#L132-L152

**Comment by candu** [comment]
@radumas this reminds me of `d3-array`'s [`tickIncrement`](https://github.com/d3/d3-array/blob/master/src/ticks.js#L34), which similarly attempts to find a nice "round" increment value.

I noticed this on [line 300](https://github.com/CityofToronto/bdit_python_utilities/blob/charts/charts/rick.py#L300), which would explain the issue @chmnata 's seeing in charts 2 and 3:

```py
ax.set_ylim([ymin,int(4*yinc+ymin)])
```

For `ymin = 0` and `ymax = 40`, the magic y tick code computes `yinc = 20`, which results here in `ax.set_ylim([0, 80])`, explaining chart 3.

For `ymin = 0` and `yinc = 5`, this line results in `ax.set_ylim([0, 20])`, explaining why chart 2 appears cut off.

**Comment by radumas** [comment]
Should we just go back to using `ymax` then?
I will revert to `ymax` and we can reopen if that doesn't solve things....
